### ISSUE TITLE
Various issues of the player in Unix

### ISSUE THREAD

**Issue by shengyun-zhou** [yet-another-graphics-engine/YaGE#6]
The player in Linux can't stop playing automatically when the song ends.

I tested the player in Linux with the follow code:

Player *player = Player::create_player("https://kirito.me/date_a_live.mp3");
player->play();
while(player->is_playing());

But the loop didn't exit when the song ended.

**Comment by xdqi** [comment]
The player cannot reset to 0 time when stopped.

**Comment by hghwng** [comment]
Closed with commit 8b9678fc34b15d00cb7cf484552faff4981a9bd9.
